name: Docker Build

on: 
  push:
    branches:
      - feature/*
jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo "Build running from default branch"
      shell: bash
    - name: Dockerbuild
      run: |-
        docker build .
