name: Docker Build

on: 
  schedule:
    - cron: '1 * * * *'
  push:
    branches:
      - feature/*
jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo "Master branch pipeline is running"
      shell: bash
    - name: Dockerbuild
      run: |-
        docker build .
