name: Docker Build

on: 
  workflow_dispatch:
  repository_dispatch:
    types: develop-package
jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo "Main develop pipeline running"
      shell: bash
    - name: Dockerbuild
      run: |-
        docker build .
