name: Docker 

on: 
  repository_dispatch:
    inputs:
      default_branch:
        description: 'Default branch to build everything'
        required: true
        type: string
        default: skip

      force_build:
        description: Ignore the last build tag and build anyway
        type: boolean
        default: false

      json_override:    
        type: string
        default: "{}"

      manifest:
        description: 'Manifest used to trigger this (informational)'
        type: string
        default: ""

jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo "Snowflake pipeline running"
      shell: bash
    - name: Dockerbuild
      run: |-
        docker build .
