name: Docker 

on: 
  workflow_dispatch:
  repository_dispatch:
    types: snowflake-package

jobs:
  Docker-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: echo "Snowflake pipeline running"
      shell: bash
    - name: Dockerbuild
      run: |-
        docker build .
